CREATE TABLE
    ip_arc_user_auth
    (
        ID CHAR(32) NOT NULL,
        STAFF_ID VARCHAR(32),
        LOGIN_ID VARCHAR(32),
        PASSWD VARCHAR(64),
        FAILED_LOGIN_COUNT DECIMAL,
        MAX_FAILED_LOGIN_COUNT DECIMAL,
        PASSWD_EXPIRE_DAYS DECIMAL,
        PASSWD_EXPIRE_DATETIME CHAR(19),
        ACCOUNT_EXPIRE_DATETIME CHAR(19),
        LAST_LOGIN_IP VARCHAR(50),
        LAST_LOGIN_DATETIME CHAR(19),
        LOGIN_IP VARCHAR(50),
        LOGIN_DATETIME CHAR(19),
        CREATOR_ID VARCHAR(32),
        CREATED_DATETIME CHAR(19),
        LAST_MODIFIER_ID VARCHAR(32),
        LAST_MODIFIED_DATETIME CHAR(19),
        DEL_FLAG CHAR(1) DEFAULT 'n',
        PRIMARY KEY (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8