CREATE TABLE
    t_biz_unitinfo
    (
        ID VARCHAR(32) NOT NULL,
        SIMPLE_NAME VARCHAR(32),
        AREA VARCHAR(32),
        PROVINCE VARCHAR(32),
        CITY VARCHAR(32),
        IC_REG_NAME VARCHAR(64),
        IC_REG_ADDRESS VARCHAR(200),
        LEGAL_PERSON VARCHAR(32),
        OPEN_DATE DATE,
        SHOP_SCALE VARCHAR(100),
        YEAR_TAST VARCHAR(32),
        RECIVER_ADDRESS VARCHAR(255),
        FAX VARCHAR(32),
        SALED_SCALE VARCHAR(100),
        JDPOWERFLAG INT,
        CSI_IMP_SHOP INT,
        UNIT_ID VARCHAR(32),
        IS_DELETED VARCHAR(1) DEFAULT '0',
        PHONE VARCHAR(20),
        RN_CODE VARCHAR(8),
        INIT_STATE INT,
        PRIMARY KEY (ID)
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8