CREATE TABLE
    vw_cas_users_base_t
    (
        USER_SRC VARCHAR(10),
        USER_ID bigint,
        USER_CODE VARCHAR(32),
        LOGIN_ID VARCHAR(32),
        USER_PSWD VARCHAR(40),
        FIRST_NAME VARCHAR(100),
        LAST_NAME VARCHAR(100),
        USER_NAME VARCHAR(100),
        USER_TYPE VARCHAR(10),
        GENDER bigint,
        IDENT_CAR_NO VARCHAR(100),
        BIRTHDAY VARCHAR(10),
        HIRE_DATE VARCHAR(10),
        LEAVE_DATE VARCHAR(10),
        OFFICE_PHONE VARCHAR(100),
        MOBILE_PHONE VARCHAR(100),
        OFFICE_EMAIL VARCHAR(100),
        PRIVY_EMAIL VARCHAR(100),
        PHOTO_FILE VARCHAR(100),
        ORG_ID bigint,
        ORG_CODE VARCHAR(100),
        COMP_ID bigint,
        COMP_CODE VARCHAR(100),
        COPI_ID bigint,
        ACTIVATE_TIME DATETIME,
        LAST_PWD_SET DATETIME,
        BAD_PWD_CNT bigint,
        LOCK_UNTIL VARCHAR(40),
        PWD_NO_EXPIRE bigint,
        FLAG_DISABLED bigint,
        FLAG_BUILTIN bigint,
        FLAG_BACK_AGENT bigint,
        CREATE_BY bigint,
        CREATE_TIME DATETIME,
        MODIFY_BY bigint,
        MODIFY_TIME DATETIME
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8