CREATE TABLE
    vw_cas_msad_domain_list_t
    (
        DOMAIN_NAME VARCHAR(30) NOT NULL,
        HOST_DNS_NAME VARCHAR(40) NOT NULL,
        HOST_IP_ADDRESS VARCHAR(20) NOT NULL,
        SVC_PORT_NUM VARCHAR(10) NOT NULL,
        SVC_WEIGHT VARCHAR(10) NOT NULL,
        SVC_PRIORITY VARCHAR(10) NOT NULL,
        SVR_TTL bigint NOT NULL,
        ROW_GEN_TYPE VARCHAR(10) NOT NULL,
        ROW_CREATED DATETIME NOT NULL
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8