CREATE TABLE
    vw_cas_msad_domain_def_t
    (
        DOMAIN_ID bit NOT NULL,
        DOMAIN_NAME VARCHAR(30) NOT NULL,
        AGENT_USER_NAME VARCHAR(10) NOT NULL,
        AGENT_USER_PSWD VARCHAR(10) NOT NULL,
        CAS_ADMIN_GROUP_CN VARCHAR(60) NOT NULL,
        ROW_CREATED DATETIME NOT NULL
    )
    ENGINE=InnoDB DEFAULT CHARSET=utf8